### PR TITLE
Support qgit and OPT/git for requirements, and better detection for g…

### PR DESCRIPTION
**Pull request by miigotu**
…it path

@Donherd could you try this package?

Packages below

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by Dohnerd** [comment]
@miigotu i freaking love you, this package installs, however when trying to open sickrage the page says ERR_CONNECTION_REFUSED.... your SOOOO close :dancer: 

I'm on the intel btw... x86

**Comment by miigotu** [comment]
port is 7073

**Comment by Dohnerd** [comment]
@miigotu yes i know... but it dosn't come up.... afterwards i checked the folder Qsickrage and it had only:
Sickbeard.sh*
bin-utils/
config/

**Comment by miigotu** [comment]
I missed a few changes, gimme a bit =P

**Comment by Dohnerd** [comment]
thing perhaps the git part is still the culprit:
5+1 records in
5+1 records out
118+1 records in
118+1 records out
QSickRage  is already installed. Setup will now perform package upgrading.
qinstall.sh: line 341: [: -gt: unary operator expected
Firmware check is fine.
Link service start/stop script: QSickRage.sh
Set QPKG information in /etc/config/qpkg.conf
x86_64
git is disabled.
[App Center] QSickRage 1.1 installation succeeded.
[App Center] QSickRage enabled.

**Comment by miigotu** [comment]
[QSickRage_1.1_x86__20160409.zip](https://github.com/SickRage/qnap-sickrage/files/211268/QSickRage_1.1_x86__20160409.zip)

**Comment by miigotu** [comment]
[QSickRage_1.1_x86__20160409.zip](https://github.com/SickRage/qnap-sickrage/files/211272/QSickRage_1.1_x86__20160409.zip)
[QSickRage_1.1_arm-x41__20160409.zip](https://github.com/SickRage/qnap-sickrage/files/211273/QSickRage_1.1_arm-x41__20160409.zip)
[QSickRage_1.1_arm-x31__20160409.zip](https://github.com/SickRage/qnap-sickrage/files/211274/QSickRage_1.1_arm-x31__20160409.zip)

**Comment by Dohnerd** [comment]
@miigotu its the same, im betting on git being the problem:

git is disabled

**Comment by miigotu** [comment]
will work at it a bit later.

tell me, whats the output of `which git`

**Comment by Dohnerd** [comment]
@miigotu /usr/bin/git

**Comment by miigotu** [comment]
edit the Qsickrage/config/config.ini and set that path in git_path var. The config.ini i bet has a path from a previous install attempt.

**Comment by miigotu** [comment]
Either way, ill work on it some more later, family trip today

**Comment by Dohnerd** [comment]
@miigotu great thanks :)
I will try to see how much I can destroy in my QNAP meanwhile :dancers:

**Comment by miigotu** [comment]
[QSickRage_1.1_arm-x31__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211629/QSickRage_1.1_arm-x31__20160410.qpkg.zip)
[QSickRage_1.1_arm-x41__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211630/QSickRage_1.1_arm-x41__20160410.qpkg.zip)
[QSickRage_1.1_x86__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211631/QSickRage_1.1_x86__20160410.qpkg.zip)

How about this one?

**Comment by Dohnerd** [comment]
@miigotu still installing but not running, installing via ssh shows:

[/share/CACHEDEV1_DATA/.qpkg/test] # sh QSickRage_1.1_x86__20160410.qpkg
Install QNAP package on TS-NAS...
./
./qinstall.sh
./package_routines
./qpkg.cfg
5+1 records in
5+1 records out
118+1 records in
118+1 records out
QSickRage  is already installed. Setup will now perform package upgrading.
Firmware check is fine.
Link service start/stop script: QSickRage.sh
Set QPKG information in /etc/config/qpkg.conf
/etc/init.d/QSickRage.sh: line 14: syntax error near unexpected token `elif'
/etc/init.d/QSickRage.sh: line 14:`elif /bin/uname -m | grep "i686|x86_64"; then'
[App Center] QSickRage 1.1 installation succeeded.
[App Center] QSickRage enabled.

And installed in QSickRage is only:

bin-utils/
config/
.list
.qpkg_icon_80.gif
.qpkg_icon_gray.gif
.uninstall.sh
QSickRage.sh

**Comment by hadim** [comment]
In QSickRage.sh in line 1 replace `sh` by `bash`.

**Comment by Dohnerd** [comment]
then the on/off button dissapears and when trying QSickRage.bash start:

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # QSickRage.bash start
./QSickRage.bash: line 14: syntax error near unexpected token `elif'
./QSickRage.bash: line 14:`elif /bin/uname -m | grep "i686|x86_64"; then'

**Comment by hadim** [comment]
Don't rename the file. Replace the string inside the file !

**Comment by Dohnerd** [comment]
There is no QSickRage.sh inside the file....

**Comment by Dohnerd** [comment]
Well so far I installed the qpkg and:

cd /share/CACHEDEV1_DATA/.qpkg/QSickRage
git init
git remote set-url origin https://github.com/SickRage/SickRage.git
GIT_SSL_NO_VERIFY=true git fetch origin
git reset --hard origin/master 

So now the directory looks more like it should but starting QSickRage.sh still gives:

./QSickRage.sh: line 14: syntax error near unexpected token `elif'
./QSickRage.sh: line 14:`elif /bin/uname -m | grep "i686|x86_64"; then'

**Comment by hadim** [comment]
1. Open the file called `shared/QSickRage.sh`
2. On the line number one of this file there is the following string : `#! /bin/sh`
3. Replace this string by the following string `#! /bin/bash`

Hope I am clear now...

**Comment by hadim** [comment]
And also what does `/bin/uname -m` return ?

**Comment by Dohnerd** [comment]
@hadim 
sh changed to bash, no difference same error

output from "/bin/uname -m":
x86_6

**Comment by miigotu** [comment]
First uninstall the package before you install new ones.

Now try this:
[QSickRage_1.1_arm-x31__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211955/QSickRage_1.1_arm-x31__20160410.qpkg.zip)
[QSickRage_1.1_arm-x41__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211957/QSickRage_1.1_arm-x41__20160410.qpkg.zip)
[QSickRage_1.1_x86__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211956/QSickRage_1.1_x86__20160410.qpkg.zip)

**Comment by Dohnerd** [comment]
@miigotu did uninstall it, but it still says its installed when i run the installer via SSH ?

I allready tried that package and it says:

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # ./QSickRage.sh start
./QSickRage.sh: line 14: syntax error near unexpected token `elif'
./QSickRage.sh: line 14:`elif /bin/uname -m | grep "i686" || /bin/uname -m | grep "x86_64"; then'

**Comment by miigotu** [comment]
sec, changing that a little bit.

**Comment by miigotu** [comment]
[Uploading QSickRage_1.1_arm-x31__20160410.qpkg.zip…]()
[QSickRage_1.1_arm-x41__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211974/QSickRage_1.1_arm-x41__20160410.qpkg.zip)
[Uploading QSickRage_1.1_x86__20160410.qpkg.zip…]()

**Comment by miigotu** [comment]
[QSickRage_1.1_arm-x31__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211985/QSickRage_1.1_arm-x31__20160410.qpkg.zip)
[QSickRage_1.1_arm-x41__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211986/QSickRage_1.1_arm-x41__20160410.qpkg.zip)
[QSickRage_1.1_x86__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/211984/QSickRage_1.1_x86__20160410.qpkg.zip)

**Comment by Dohnerd** [comment]
@miigotu  still im only getting following files in the QSickRage directory:

bin-utils/
config/
.list
.qpkg_icon_80.gif
.qpkg_icon_gray.gif
.uninstall.sh
QSickRage.sh

Could it be some problem with the SSL on Qnap (I know its a bitch) .....

And still not working ....

**Comment by Dohnerd** [comment]
@miigotu 
[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # ./QSickRage.sh start
QSickRage prestartup checks...
 Checking for git...Git Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.9 at /opt/QPython2/bin/python2.7
Updating QSickRage
./QSickRage.sh: line 121: git_path: command not found
./QSickRage.sh: line 121: git_path: command not found
./QSickRage.sh: line 122: cd: /share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage: No such file or directory
Starting QSickRage
./QSickRage.sh: line 127: cd: /share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage: No such file or directory
/opt/QPython2/bin/python2.7: can't open file 'SickBeard.py': [Errno 2] No such file or directory

**Comment by Dohnerd** [comment]
@miigotu ok got it up and running, had to do a "dirty fix".....

I had a old Sickrage-4.1.0 laying around from my previous Qnap, so i copied the contents to QSickRage and renamed sickrage folder to QSickRage (as i saw that was the one you wanted)... and boom after 5 days its up and running.......

**Comment by Dohnerd** [comment]
@miigotu now a last quick question... where do i put config.ini and sickbeard.db from old install ?

**Comment by miigotu** [comment]
Copying the files from the old install doesnt fix the package.

I want to finish fixing the package correctly, so other ppl can benefit.

**Comment by Dohnerd** [comment]
Yeah and it only worked shortly stopped and started it from App center and poof it didn't work anymore

**Comment by miigotu** [comment]
[QSickRage_1.1_arm-x31__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/212008/QSickRage_1.1_arm-x31__20160410.qpkg.zip)
[QSickRage_1.1_arm-x41__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/212009/QSickRage_1.1_arm-x41__20160410.qpkg.zip)
[QSickRage_1.1_x86__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/212010/QSickRage_1.1_x86__20160410.qpkg.zip)

**Comment by Dohnerd** [comment]
@miigotu we are getting closer, but not quite there:

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # ./QSickRage.sh start
QSickRage prestartup checks...
 Checking for git...Git Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.9 at /opt/QPython2/bin/python2.7
Updating QSickRage
Cloning into '/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into '/share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage'...
fatal: Unable to find remote helper for 'https'
./QSickRage.sh: line 122: cd: /share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage: No such file or directory
Starting QSickRage
./QSickRage.sh: line 127: cd: /share/CACHEDEV1_DATA/.qpkg/QSickRage/QSickRage: No such file or directory
/opt/QPython2/bin/python2.7: can't open file 'SickBeard.py': [Errno 2] No such file or directory

**Comment by miigotu** [comment]
Thats a problem with your git install now.

**Comment by Dohnerd** [comment]
@miigotu i actually think its a problem with the new way QNAP handles SSL.... git is working fine, but all SSL is sh*t ....

**Comment by miigotu** [comment]
[QSickRage_1.1_arm-x31__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/212044/QSickRage_1.1_arm-x31__20160410.qpkg.zip)
[QSickRage_1.1_arm-x41__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/212042/QSickRage_1.1_arm-x41__20160410.qpkg.zip)
[QSickRage_1.1_x86__20160410.qpkg.zip](https://github.com/SickRage/qnap-sickrage/files/212043/QSickRage_1.1_x86__20160410.qpkg.zip)

**Comment by Dohnerd** [comment]
@miigotu this installs and starts web..... cool....

I will check it tomorrow or maybe later tonight and see if its stable :)

**Comment by miigotu** [comment]
Except since https doesnt work on the qnap, Im not so sure any https sites will work inside SR lol. it might be useless

**Comment by Dohnerd** [comment]
@miigotu  yeah i can see its not doing anything if you search for updates...

**Comment by Dohnerd** [comment]
@miigotu  Also unable to get schedule

**Comment by miigotu** [comment]
Which is why you are supposed to install the normal qnap git, it installs the dependencies for https

**Comment by Dohnerd** [comment]
@miigotu i have installed Qgit_2.7.4_x86.qpkg isn't that the "normal" git?
I think its because Qnap has gone mad with the new QTS 4.2 it has crazy SSL restrictions, I'm hoping to find someone who knows how to add SSL dependencies for sickrage :/

**Comment by Dohnerd** [comment]
@miigotu BOOOMMM disabled SSL and now updates etc. are working... I f_ck_ng love you mate :D

**Comment by jkeroes** [comment]
should this be merged?

**Comment by miigotu** [comment]
dont know, I dont have a qnap and I dont think I finished this PR

**Comment by clinton-hall** [comment]
@miigotu @hadim 
I hadn't even realised my old Apps were still being used as the base here.... when the `QSickRage` version came along I thought there was a new maintainer....

For history here, I compiled git as opt was not longer being supported and existing git apps were obsolete... but clearly now mine is the obsolete one... so these changes to move away from my git are needed. I had tried to get my apps installed into /Apps/bin/ because everything else at the time was in /opt/ or linked into /bin/ and was a mess of conflicting versions. I tried to set up a clean system to link compatible Apps... but no-one seemed to go for it, containers were being introduced at the time, and I got busy/burnt out...

I can probably set up some test QNAP models (and provide SSH access) if that would ever be of benefit to test any of these things.

**Comment by miigotu** [comment]
@clinton-hall I still need to go through this and rename all references from SickRage to SickChill. I will avoid conflicts with his code on as many devices as possible, or he might find a way to mess with peoples config somewhere in the future.

**Pull request closed without merging**
